/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import static dbase.bdd.Setconnection;
import static dbase.bdd.con;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import static jdk.nashorn.internal.runtime.Debug.id;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import java.awt.BorderLayout;


public class cure extends javax.swing.JFrame {
	
	

    /**
     * Creates new form cure
     */
    public cure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(9, 229, 162));
        
        JLabel lblHeureEtDate = new JLabel();
        lblHeureEtDate.setForeground(Color.RED);
        lblHeureEtDate.setText("Heure et Date");
        lblHeureEtDate.setFont(new Font("Dialog", Font.BOLD, 18));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(125)
        			.addComponent(lblHeureEtDate, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblHeureEtDate, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        			.addGap(24))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), new java.awt.Color(0, 153, 204)), "Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Garamond", 1, 18), new java.awt.Color(51, 102, 255))); // NOI18N
        jPanel14.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel32.setText("Date ");

        jLabel33.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel33.setText("Heure");

        jComboBox1.setEditable(true);
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });

        dateChooserCombo1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.LOWERED,
            (java.awt.Color)null,
            (java.awt.Color)null));

    javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
    jPanel14Layout.setHorizontalGroup(
    	jPanel14Layout.createParallelGroup(Alignment.LEADING)
    		.addGroup(jPanel14Layout.createSequentialGroup()
    			.addContainerGap()
    			.addGroup(jPanel14Layout.createParallelGroup(Alignment.TRAILING, false)
    				.addComponent(jLabel32, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 110, Short.MAX_VALUE)
    				.addComponent(jLabel33, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    			.addGap(18)
    			.addGroup(jPanel14Layout.createParallelGroup(Alignment.LEADING)
    				.addComponent(jComboBox1, 0, 215, Short.MAX_VALUE)
    				.addComponent(dateChooserCombo1, GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
    			.addContainerGap())
    );
    jPanel14Layout.setVerticalGroup(
    	jPanel14Layout.createParallelGroup(Alignment.TRAILING)
    		.addGroup(jPanel14Layout.createSequentialGroup()
    			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    			.addGroup(jPanel14Layout.createParallelGroup(Alignment.LEADING, false)
    				.addComponent(dateChooserCombo1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
    				.addGroup(jPanel14Layout.createSequentialGroup()
    					.addComponent(jLabel32, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    					.addGap(5)))
    			.addPreferredGap(ComponentPlacement.RELATED)
    			.addGroup(jPanel14Layout.createParallelGroup(Alignment.LEADING)
    				.addComponent(jLabel33, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
    				.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
    			.addGap(354))
    );
    jLabel2 = new javax.swing.JLabel();
    dateChooserCombo1.add(jLabel2, BorderLayout.NORTH);
    
        jLabel2.setFont(new java.awt.Font("Tiger Expert", 0, 18));
    jPanel14.setLayout(jPanel14Layout);

    jButton1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ok.png"))); // NOI18N
    jButton1.setText("Enregistrer");
    jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2Layout.setHorizontalGroup(
    	jPanel2Layout.createParallelGroup(Alignment.LEADING)
    		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
    			.addContainerGap()
    			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
    				.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    				.addComponent(jButton1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
    				.addComponent(jPanel14, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
    			.addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
    	jPanel2Layout.createParallelGroup(Alignment.LEADING)
    		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
    			.addContainerGap()
    			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    			.addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.RELATED)
    			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
    			.addGap(76))
    );
    jPanel2.setLayout(jPanel2Layout);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    layout.setHorizontalGroup(
    	layout.createParallelGroup(Alignment.LEADING)
    		.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
    	layout.createParallelGroup(Alignment.LEADING)
    		.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
    );
    getContentPane().setLayout(layout);

    pack();
    }// </editor-fold>//GEN-END:initComponents
 public void filter_client(JComboBox c) 
    {
        
        
        
         try {
             Setconnection();
             c.removeAllItems();
             AutoCompleteDecorator.decorate(c);
             
             //Setconnection();
             Statement stmt=con.createStatement();
             String select="select * from patient";
             ResultSet rs=stmt.executeQuery(select);
             while(rs.next())
             {
                 c.addItem(""+rs.getString(1));
             }
             c.setSelectedItem("");
             con.close(); 
         } catch (SQLException ex) {
             Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
         }
            }
  public void getClient(int c,JLabel l) 
    {
        
        
        
         try {
             Setconnection();
            
             //Setconnection();
             Statement stmt=con.createStatement();
             String select="select nom,prenom from patient where id= '"+c+"' ";
             ResultSet rs=stmt.executeQuery(select);
             while(rs.next())
             {
                 l.setText("Mr/"+rs.getString(1)+" "+rs.getString(2));
         
             }
             con.close(); 
         } catch (SQLException ex) {
             Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
         }
            }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        filter_client(jComboBox1);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
 int c=new Integer(jComboBox1.getSelectedItem().toString()).intValue();
        
        getClient(c, jLabel2);

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped

    }//GEN-LAST:event_jComboBox1KeyTyped

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
       
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s=dateChooserCombo1.getText();
        System.out.print(s);
        
        int c=new Integer(jComboBox1.getSelectedItem().toString()).intValue();
        
        getClient(c, jLabel2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
 int c=new Integer(jComboBox1.getSelectedItem().toString()).intValue();
        
        getClient(c, jLabel2);        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
}
